MVCBank/Models/Transferencia.cs
namespace MVCBank.Models
{
    public class Transferencia
    {
        public int IdAccountSender { get; set; }
        public int IdAccountReceiver { get; set; }
        public float Amount { get; set; }
        public DateTime DateIssue { get; set; }
    }
}

MVCBank/Controllers/NormUserController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MVCBank.Models;
using BankSystem.Web.Servicios;
using MVCBank.Servicios;
using System.Runtime.CompilerServices;

namespace MVCBank.Controllers
{
    public class NormUserController : Controller
    {
        private readonly IServicio_API_User servicioAPI;
        private readonly IServicio_API_BAccount servicio_APIBAccount;
        private readonly IServicio_API_Transferencia transferenciaAPI;
        public NormUserController(IServicio_API_User servicioAPI, IServicio_API_BAccount servicio_APIBAccount,
            IServicio_API_Transferencia transferenciaAPI)
        {
            this.servicioAPI = servicioAPI;
            this.servicio_APIBAccount = servicio_APIBAccount;
            this.transferenciaAPI = transferenciaAPI;

        }

        // GET: NormUserController
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Index(string Email, string Password)

        {
            
            var response = await servicioAPI.Autenticar(Email, Password);
            Console.WriteLine("hola " + response?.IdUser);

            if (response != null)
            {
                if (response.Role.Equals("client"))
                {
                    var response2 = await servicio_APIBAccount.GetIdUser((int)(response?.IdUser));
                    Console.WriteLine("Resp" + response2?.IdUser);
                    return View("Details", response2);
                }
                else
                {
                    return RedirectToAction("Index", "Admin", response);
                }



            }
            return View();
        }

        // GET: NormUserController/Details/5
        public IActionResult Details(BankAccount account)
        {
            if (account != null)
            {
                Console.WriteLine("con" + account.IdUser);
                return View(account);
            }
            return RedirectToAction("Index");
        }


        public async Task<IActionResult> DetailsBack(int IdAccount)
        {

            var account = await servicio_APIBAccount.Obtener(IdAccount);
            if (account != null)
            {
                Console.WriteLine("con" + account.IdUser);
                return View("Details", account);
            }
            return RedirectToAction("Index");
        }

        public IActionResult Create()
        {
            return View();
        }


        [HttpPost]
        public async Task<IActionResult> Create(User user)
        {

            user.IdUser = 0;
            user.Name = user.Name;
            user.Phone = user.Phone;
            user.DNI= user.DNI;

            user.Role = user.Role.Equals("Cliente") ? "client" : "admin";

            var response = await servicioAPI.Crear(user);
            Console.WriteLine(response.ToString());

                Console.WriteLine(user.Password + "hola");
            if (response != 0)
            {
                BankAccount account = new BankAccount();
                var lista = await servicio_APIBAccount.Lista();
                account.AccountNumber = lista.Count + 1;
                account.AccountAmount = 0;
                account.IdUser = response;
                var response2 = await servicio_APIBAccount.Guardar(account);

            return View("Index");

            } 
                
            return View();

        }

 

        
        public async Task<ActionResult> Edit(int IdAccount)
        {

            var response = await servicio_APIBAccount.Obtener(IdAccount);
            Console.WriteLine("hola" + response?.IdUser);
            if (response?.IdUser != 0)
            {
                Transferencia transfer = new Transferencia() { Amount = 0, IdAccountSender = response.IdAccount, IdAccountReceiver = 0 };

                return View("Edit", transfer);


            }
            return View();

        }

        [HttpPost]
        public async Task<IActionResult> Edit(Transferencia transfer)

        {
            Transferencia transfer1 = null;
            if (transfer != null)
            {
                transfer.IdTransfer = 0;
                transfer.DateIssue = DateTime.Now;
                BankAccount accountSender = await servicio_APIBAccount.Obtener(transfer.IdAccountSender);
                BankAccount accountReceiver = await servicio_APIBAccount.Obtener(transfer.IdAccountReceiver);
                Console.WriteLine(transfer.ToString + "accountS");
                Console.WriteLine(accountSender.AccountAmount +"accountS");
                Console.WriteLine(accountReceiver.AccountAmount + "accountR");
                if (accountReceiver != null)
                {
                    transfer1 = transfer;
                    bool trans=true;
                    BankAccount test = await servicio_APIBAccount.EditarCantidad(accountReceiver.IdAccount,
                        accountReceiver.AccountAmount + transfer.Amount);
                    BankAccount test2 = await servicio_APIBAccount.EditarCantidad(accountSender.IdAccount,
                        accountSender.AccountAmount - transfer.Amount);
                    await transferenciaAPI.Crear(transfer);
                    Console.WriteLine(test.AccountAmount + "Test");
                    Console.WriteLine(test2.AccountAmount + "Test");
                    Console.WriteLine("Transferencia emitida: ");
                    return View("Details", accountSender);
                }
            }
            Console.WriteLine("Operacion fallida");
            return BadRequest("No se pudo realizar la accion");
        }

        // GET: NormUserController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }
        // Transferencia
        public async Task<IActionResult> Transferencias(int IdAccount)
        {
            List<Transferencia> transfer = await transferenciaAPI.Transferencias(IdAccount);
            ViewData["IdAccount"] = IdAccount;
            return View("Transferencias", transfer);

        }
        // POST: NormUserController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

MVCBank/Views/NormUser/Create.cshtml
@model User

<link href="~/css/site.css" rel="stylesheet" />
<link href="~/css/style.css" rel="stylesheet" />

<title>Registro de usuario</title>

<h2>@ViewData["Title"]</h2>
<div>
    <form method="post" autocomplete="on" class="mb-3">
        <div class="col-md-6">
            <label>Nombre de usuario:</label>
            <input asp-for="Name" type="text"  class="form-control" required />
        </div>
        <div class="col-md-6">   
            <label>Email:</label>
            <input asp-for="Email" type="email" class="form-control" required />
        </div>
        <div class="col-md-6">
            <label>Ingrese una contraseña:</label>
            <input asp-for="Password" class="form-control" type="password" required />
        </div>
        <div class="col-md-6">
            <label>Número de teléfono:</label>
            <input asp-for="Phone" type="text" class="form-control" required />
        </div>
        <div class="col-md-6">
            <label>DNI:</label>
            <input asp-for="DNI" type="text" class="form-control" required />
        </div>
        <div class="col-md-6">
            <label>Rol:</label>
            <select class="form-select" asp-for="Role">
                <option selected>Cliente</option>
                <option value="1">Administrador</option>
            </select>
        </div>

        <div style="margin-top: 2rem;">
            <a asp-action="Index" asp-controller="Home" class="btn btn-danger">Cancelar</a>
            <button asp-action="Create" asp-asp-controller="NormUser" type="submit" class="btn btn-success">Registrarse</button>
        </div>
    </form>

</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>

MVCBank/Views/NormUser/Details.cshtml
@model BankAccount

@{
    ViewData["Title"] = "Estado de cuenta";
}

<link href="~/css/site.css" rel="stylesheet" />
<link href="~/css/style.css" rel="stylesheet" />

    <div class="card" style="width: 18rem;">
        <h2>@ViewData["Title"]</h2>
        <div class="card-body">
            <h4>Cuenta de ahorro</h4>
            <table class="table table-borderless">
                <tr>
                    <td>Número de cuenta:</td>
                    <td></td>
                    <td></td>
                    <td>@Model.AccountNumber</td>
                </tr>
                <tr>
                    <td>Saldo disponible:</td>
                    <td></td>
                    <td></td>
                    <td>$@Model.AccountAmount</td>
                </tr>
            </table>
        </div>
    </div>

    <div class="btn-group" style="margin-top: 2rem;">
        <a type="button" asp-action="Edit" asp-route-IdAccount="@Model.IdAccount" class="btn btn-success" >Transferencias</a>
        <a type="button" asp-action="Transferencias" asp-route-IdAccount="@Model.IdAccount" class="btn btn-primary" >Lista de Transferencias</a>
        <a asp-action="Index" asp-controller="Home" class="btn btn-danger">Cerrar Sesión</a>
    </div>

MVCBank/Views/NormUser/Edit.cshtml
@model Transferencia

@{
    ViewData["Title"] = "Transferencias";
}

<link href="~/css/site.css" rel="stylesheet" />
<link href="~/css/style.css" rel="stylesheet" />

<div Class="pt-16 px-16">
    <h3>@ViewData["Title"]</h3>
    
    <form method="post" autocomplete="on">
        <div class="d-inline pa-2">
            <h4>Cuenta de ahorros</h4>
            <label style="font-size: 16px">@Model.IdAccountSender</label>
        </div>
        <div style="margin-top: 10%;">
            <label>Monto:</label>
            <div class="input-group">
                <div class="input-group-prepend">
                    <span class="input-group-text">$</span>
                </div>
                <input asp-for="Amount" class="form-control" required />
            </div>

            <div class="input-group">
                @* <label>Nombre del beneficiario:<input type="text" class="form-control" readonly /></label>*@
                <label>Número de cuenta:</label>
                <input asp-for="IdAccountReceiver" class="form-control" required />
                @*<button class="btn btn-warning form-control position-absolute bottom-0 start-50" style="width: 10%;">Validar</button>*@
            </div>
        </div>
        <input asp-for="IdAccountSender" class="form-control" hidden/>
        <div class="btn-group" role="group" style="margin-top: 2rem;">
            <button class="btn btn-danger" asp-action="DetailsBack" asp-controller="NormUser" asp-route-IdAccount="@Model.IdAccountSender">Cancelar</button>
            <button type="submit" class="btn btn-success">Transferir</button>
        </div>
    </form>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>

MVCBank/Views/NormUser/Index.cshtml
@model User
@{
    ViewData["Title"] = "Iniciar Sesion";
}

<link href="~/css/site.css" rel="stylesheet" />
<link href="~/css/style.css" rel="stylesheet" />

<h3>Iniciar sesion</h3>

<div>
    <form method="post" autocomplete="on">
        <div class="form-control">
            <label>Email:</label>
            <input asp-for="Email" class="form-control" type="email" required />
            <label>Contraseña:</label>
            <input asp-for="Password" class="form-control" type="password" required />
        </div>
        <div style="margin-top: 2rem;">
            <button type="submit" asp-action="Index" class="btn btn-success">Ingresar</button>
            <a asp-action="Index" asp-controller="Home" class="btn btn-danger">Regresar</a>
        </div>
    </form>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>

MVCBank/Views/NormUser/Transferencias.cshtml
@model List<Transferencia>
@{
    int? IdAccount = ViewData["IdAccount"] as int?;
}

<link href="~/css/site.css" rel="stylesheet" />
<link href="~/css/style.css" rel="stylesheet" />

<body>
    @foreach (var transfer in Model)
    {
        <div class="card">
            <div class="card-header">
                Detalles de la transferencia
            </div>
            <div class="card-body">
                <h5 class="card-title">Transferencia ID: @transfer.IdTransfer</h5>
                <div class="card-text">
                    <div class="modal-body">
                        <div class="col-sm-6">
                            <label>ID de la cuenta remitente:</label>
                            <input class="form-control" asp-for="@transfer.IdAccountSender" readonly />
                        </div>
                        <div class="col-sm-6">
                            <label>ID de la cuenta receptora:</label>
                            <input class="form-control" asp-for="@transfer.IdAccountReceiver" readonly />
                        </div>
                        <div class="col-sm-6">
                            <label>Monto:</label>
                            <input class="form-control" asp-for="@transfer.Amount" readonly />
                        </div>
                        <div class="col-sm-6">
                            <label>Fecha de emisión:</label>
                            <input class="form-control" asp-for="@transfer.DateIssue" readonly />
                        </div>
                    </div>
                </div>
               
            </div>
        </div>
    }
    <a class="btn btn-danger" style="margin-top: 2rem;" asp-controller="NormUser" asp-action="DetailsBack" asp-route-IdAccount="@IdAccount"> Volver </a>
</body>